#ifndef _SYSTEM_DRAWING_PRINTING_PAGERKIND_H_
#define _SYSTEM_DRAWING_PRINTING_PAGERKIND_H_

namespace Aspose {
	namespace Cells {
		namespace System{
			namespace Drawing {
				namespace Printing {
					enum PaperKind
					{
						PaperKind_A2 = 66,
						PaperKind_A3 = 8,
						PaperKind_A3Extra = 63,
						PaperKind_A3ExtraTransverse = 68,
						PaperKind_A3Rotated = 76,
						PaperKind_A3Transverse = 67,
						PaperKind_A4 = 9,
						PaperKind_A4Extra = 53,
						PaperKind_A4Plus = 60,
						PaperKind_A4Rotated = 77,
						PaperKind_A4Small = 10,
						PaperKind_A4Transverse = 55,
						PaperKind_A5 = 11,
						PaperKind_A5Extra = 64,
						PaperKind_A5Rotated = 78,
						PaperKind_A5Transverse = 61,
						PaperKind_A6 = 70,
						PaperKind_A6Rotated = 83,
						PaperKind_APlus = 57,
						PaperKind_B4 = 12,
						PaperKind_B4Envelope = 33,
						PaperKind_B4JisRotated = 79,
						PaperKind_B5 = 13,
						PaperKind_B5Envelope = 34,
						PaperKind_B5Extra = 65,
						PaperKind_B5JisRotated = 80,
						PaperKind_B5Transverse = 62,
						PaperKind_B6Envelope = 35,
						PaperKind_B6Jis = 88,
						PaperKind_B6JisRotated = 89,
						PaperKind_BPlus = 58,
						PaperKind_C3Envelope = 29,
						PaperKind_C4Envelope = 30,
						PaperKind_C5Envelope = 28,
						PaperKind_C65Envelope = 32,
						PaperKind_C6Envelope = 31,
						PaperKind_CSheet = 24,
						PaperKind_Custom = 0,
						PaperKind_DLEnvelope = 27,
						PaperKind_DSheet = 25,
						PaperKind_ESheet = 26,
						PaperKind_Executive = 7,
						PaperKind_Folio = 14,
						PaperKind_GermanLegalFanfold = 41,
						PaperKind_GermanStandardFanfold = 40,
						PaperKind_InviteEnvelope = 47,
						PaperKind_IsoB4 = 42,
						PaperKind_ItalyEnvelope = 36,
						PaperKind_JapaneseDoublePostcard = 69,
						PaperKind_JapaneseDoublePostcardRotated = 82,
						PaperKind_JapaneseEnvelopeChouNumber3 = 73,
						PaperKind_JapaneseEnvelopeChouNumber3Rotated = 86,
						PaperKind_JapaneseEnvelopeChouNumber4 = 74,
						PaperKind_JapaneseEnvelopeChouNumber4Rotated = 87,
						PaperKind_JapaneseEnvelopeKakuNumber2 = 71,
						PaperKind_JapaneseEnvelopeKakuNumber2Rotated = 84,
						PaperKind_JapaneseEnvelopeKakuNumber3 = 72,
						PaperKind_JapaneseEnvelopeKakuNumber3Rotated = 85,
						PaperKind_JapaneseEnvelopeYouNumber4 = 91,
						PaperKind_JapaneseEnvelopeYouNumber4Rotated = 92,
						PaperKind_JapanesePostcard = 43,
						PaperKind_JapanesePostcardRotated = 81,
						PaperKind_Ledger = 4,
						PaperKind_Legal = 5,
						PaperKind_LegalExtra = 51,
						PaperKind_Letter = 1,
						PaperKind_LetterExtra = 50,
						PaperKind_LetterExtraTransverse = 56,
						PaperKind_LetterPlus = 59,
						PaperKind_LetterRotated = 75,
						PaperKind_LetterSmall = 2,
						PaperKind_LetterTransverse = 54,
						PaperKind_MonarchEnvelope = 37,
						PaperKind_Note = 18,
						PaperKind_Number10Envelope = 20,
						PaperKind_Number11Envelope = 21,
						PaperKind_Number12Envelope = 22,
						PaperKind_Number14Envelope = 23,
						PaperKind_Number9Envelope = 19,
						PaperKind_PersonalEnvelope = 38,
						PaperKind_Prc16K = 93,
						PaperKind_Prc16KRotated = 106,
						PaperKind_Prc32K = 94,
						PaperKind_Prc32KBig = 95,
						PaperKind_Prc32KBigRotated = 108,
						PaperKind_Prc32KRotated = 107,
						PaperKind_PrcEnvelopeNumber1 = 96,
						PaperKind_PrcEnvelopeNumber10 = 105,
						PaperKind_PrcEnvelopeNumber10Rotated = 118,
						PaperKind_PrcEnvelopeNumber1Rotated = 109,
						PaperKind_PrcEnvelopeNumber2 = 97,
						PaperKind_PrcEnvelopeNumber2Rotated = 110,
						PaperKind_PrcEnvelopeNumber3 = 98,
						PaperKind_PrcEnvelopeNumber3Rotated = 111,
						PaperKind_PrcEnvelopeNumber4 = 99,
						PaperKind_PrcEnvelopeNumber4Rotated = 112,
						PaperKind_PrcEnvelopeNumber5 = 100,
						PaperKind_PrcEnvelopeNumber5Rotated = 113,
						PaperKind_PrcEnvelopeNumber6 = 101,
						PaperKind_PrcEnvelopeNumber6Rotated = 114,
						PaperKind_PrcEnvelopeNumber7 = 102,
						PaperKind_PrcEnvelopeNumber7Rotated = 115,
						PaperKind_PrcEnvelopeNumber8 = 103,
						PaperKind_PrcEnvelopeNumber8Rotated = 116,
						PaperKind_PrcEnvelopeNumber9 = 104,
						PaperKind_PrcEnvelopeNumber9Rotated = 117,
						PaperKind_Quarto = 15,
						PaperKind_Standard10x11 = 45,
						PaperKind_Standard10x14 = 16,
						PaperKind_Standard11x17 = 17,
						PaperKind_Standard12x11 = 90,
						PaperKind_Standard15x11 = 46,
						PaperKind_Standard9x11 = 44,
						PaperKind_Statement = 6,
						PaperKind_Tabloid = 3,
						PaperKind_TabloidExtra = 52,
						PaperKind_USStandardFanfold = 39
					};
				}

			}
		}
	}
}
#endif
