#pragma once
namespace Aspose {
namespace Cells {
namespace Charts {
	enum ChartType 

	{

			ChartType_Area ,
			ChartType_AreaStacked ,
			ChartType_Area100PercentStacked ,
			ChartType_Area3D ,
			ChartType_Area3DStacked ,
			ChartType_Area3D100PercentStacked ,
			ChartType_Bar ,
			ChartType_BarStacked ,
			ChartType_Bar100PercentStacked ,
			ChartType_Bar3DClustered ,
			ChartType_Bar3DStacked ,
			ChartType_Bar3D100PercentStacked ,
			ChartType_Bubble ,
			ChartType_Bubble3D ,
			ChartType_Column ,
			ChartType_ColumnStacked ,
			ChartType_Column100PercentStacked ,
			ChartType_Column3D ,
			ChartType_Column3DClustered ,
			ChartType_Column3DStacked ,
			ChartType_Column3D100PercentStacked ,
			ChartType_Cone ,
			ChartType_ConeStacked ,
			ChartType_Cone100PercentStacked ,
			ChartType_ConicalBar ,
			ChartType_ConicalBarStacked ,
			ChartType_ConicalBar100PercentStacked ,
			ChartType_ConicalColumn3D ,
			ChartType_Cylinder ,
			ChartType_CylinderStacked ,
			ChartType_Cylinder100PercentStacked ,
			ChartType_CylindricalBar ,
			ChartType_CylindricalBarStacked ,
			ChartType_CylindricalBar100PercentStacked ,
			ChartType_CylindricalColumn3D ,
			ChartType_Doughnut ,
			ChartType_DoughnutExploded ,
			ChartType_Line ,
			ChartType_LineStacked ,
			ChartType_Line100PercentStacked ,
			ChartType_LineWithDataMarkers ,
			ChartType_LineStackedWithDataMarkers ,
			ChartType_Line100PercentStackedWithDataMarkers ,
			ChartType_Line3D ,
			ChartType_Pie ,
			ChartType_Pie3D ,
			ChartType_PiePie ,
			ChartType_PieExploded ,
			ChartType_Pie3DExploded ,
			ChartType_PieBar ,
			ChartType_Pyramid ,
			ChartType_PyramidStacked ,
			ChartType_Pyramid100PercentStacked ,
			ChartType_PyramidBar ,
			ChartType_PyramidBarStacked ,
			ChartType_PyramidBar100PercentStacked ,
			ChartType_PyramidColumn3D ,
			ChartType_Radar ,
			ChartType_RadarWithDataMarkers ,
			ChartType_RadarFilled ,
			ChartType_Scatter ,
			ChartType_ScatterConnectedByCurvesWithDataMarker ,
			ChartType_ScatterConnectedByCurvesWithoutDataMarker ,
			ChartType_ScatterConnectedByLinesWithDataMarker ,
			ChartType_ScatterConnectedByLinesWithoutDataMarker ,
			ChartType_StockHighLowClose ,
			ChartType_StockOpenHighLowClose ,
			ChartType_StockVolumeHighLowClose ,
			ChartType_StockVolumeOpenHighLowClose ,
			ChartType_Surface3D ,
			ChartType_SurfaceWireframe3D ,
			ChartType_SurfaceContour ,
			ChartType_SurfaceContourWireframe ,
	};


}

}

}
