#pragma once
namespace Aspose {
namespace Cells {
	enum PaperSizeType 

	{

			PaperSizeType_PaperLetter = 1 ,
			PaperSizeType_PaperLetterSmall = 2 ,
			PaperSizeType_PaperTabloid = 3 ,
			PaperSizeType_PaperLedger = 4 ,
			PaperSizeType_PaperLegal = 5 ,
			PaperSizeType_PaperStatement = 6 ,
			PaperSizeType_PaperExecutive = 7 ,
			PaperSizeType_PaperA3 = 8 ,
			PaperSizeType_PaperA4 = 9 ,
			PaperSizeType_PaperA4Small = 10 ,
			PaperSizeType_PaperA5 = 11 ,
			PaperSizeType_PaperB4 = 12 ,
			PaperSizeType_PaperB5 = 13 ,
			PaperSizeType_PaperFolio = 14 ,
			PaperSizeType_PaperQuarto = 15 ,
			PaperSizeType_Paper10x14 = 16 ,
			PaperSizeType_Paper11x17 = 17 ,
			PaperSizeType_PaperNote = 18 ,
			PaperSizeType_PaperEnvelope9 = 19 ,
			PaperSizeType_PaperEnvelope10 = 20 ,
			PaperSizeType_PaperEnvelope11 = 21 ,
			PaperSizeType_PaperEnvelope12 = 22 ,
			PaperSizeType_PaperEnvelope14 = 23 ,
			PaperSizeType_PaperCSheet = 24 ,
			PaperSizeType_PaperDSheet = 25 ,
			PaperSizeType_PaperESheet = 26 ,
			PaperSizeType_PaperEnvelopeDL = 27 ,
			PaperSizeType_PaperEnvelopeC5 = 28 ,
			PaperSizeType_PaperEnvelopeC3 = 29 ,
			PaperSizeType_PaperEnvelopeC4 = 30 ,
			PaperSizeType_PaperEnvelopeC6 = 31 ,
			PaperSizeType_PaperEnvelopeC65 = 32 ,
			PaperSizeType_PaperEnvelopeB4 = 33 ,
			PaperSizeType_PaperEnvelopeB5 = 34 ,
			PaperSizeType_PaperEnvelopeB6 = 35 ,
			PaperSizeType_PaperEnvelopeItaly = 36 ,
			PaperSizeType_PaperEnvelopeMonarch = 37 ,
			PaperSizeType_PaperEnvelopePersonal = 38 ,
			PaperSizeType_PaperFanfoldUS = 39 ,
			PaperSizeType_PaperFanfoldStdGerman = 40 ,
			PaperSizeType_PaperFanfoldLegalGerman = 41 ,
			PaperSizeType_PaperISOB4 = 42 ,
			PaperSizeType_PaperJapanesePostcard = 43 ,
			PaperSizeType_Paper9x11 = 44 ,
			PaperSizeType_Paper10x11 = 45 ,
			PaperSizeType_Paper15x11 = 46 ,
			PaperSizeType_PaperEnvelopeInvite = 47 ,
			PaperSizeType_PaperLetterExtra = 50 ,
			PaperSizeType_PaperLegalExtra = 51 ,
			PaperSizeType_PaperTabloidExtra = 52 ,
			PaperSizeType_PaperA4Extra = 53 ,
			PaperSizeType_PaperLetterTransverse = 54 ,
			PaperSizeType_PaperA4Transverse = 55 ,
			PaperSizeType_PaperLetterExtraTransverse = 56 ,
			PaperSizeType_PaperSuperA = 57 ,
			PaperSizeType_PaperSuperB = 58 ,
			PaperSizeType_PaperLetterPlus = 59 ,
			PaperSizeType_PaperA4Plus = 60 ,
			PaperSizeType_PaperA5Transverse = 61 ,
			PaperSizeType_PaperJISB5Transverse = 62 ,
			PaperSizeType_PaperA3Extra = 63 ,
			PaperSizeType_PaperA5Extra = 64 ,
			PaperSizeType_PaperISOB5Extra = 65 ,
			PaperSizeType_PaperA2 = 66 ,
			PaperSizeType_PaperA3Transverse = 67 ,
			PaperSizeType_PaperA3ExtraTransverse = 68 ,
			PaperSizeType_PaperJapaneseDoublePostcard = 69 ,
			PaperSizeType_PaperA6 = 70 ,
			PaperSizeType_PaperJapaneseEnvelopeKaku2 = 71 ,
			PaperSizeType_PaperJapaneseEnvelopeKaku3 = 72 ,
			PaperSizeType_PaperJapaneseEnvelopeChou3 = 73 ,
			PaperSizeType_PaperJapaneseEnvelopeChou4 = 74 ,
			PaperSizeType_PaperLetterRotated = 75 ,
			PaperSizeType_PaperA3Rotated = 76 ,
			PaperSizeType_PaperA4Rotated = 77 ,
			PaperSizeType_PaperA5Rotated = 78 ,
			PaperSizeType_PaperJISB4Rotated = 79 ,
			PaperSizeType_PaperJISB5Rotated = 80 ,
			PaperSizeType_PaperJapanesePostcardRotated = 81 ,
			PaperSizeType_PaperJapaneseDoublePostcardRotated = 82 ,
			PaperSizeType_PaperA6Rotated = 83 ,
			PaperSizeType_PaperJapaneseEnvelopeKaku2Rotated = 84 ,
			PaperSizeType_PaperJapaneseEnvelopeKaku3Rotated = 85 ,
			PaperSizeType_PaperJapaneseEnvelopeChou3Rotated = 86 ,
			PaperSizeType_PaperJapaneseEnvelopeChou4Rotated = 87 ,
			PaperSizeType_PaperJISB6 = 88 ,
			PaperSizeType_PaperJISB6Rotated = 89 ,
			PaperSizeType_Paper12x11 = 90 ,
			PaperSizeType_PaperJapaneseEnvelopeYou4 = 91 ,
			PaperSizeType_PaperJapaneseEnvelopeYou4Rotated = 92 ,
			PaperSizeType_PaperPRC16K = 93 ,
			PaperSizeType_PaperPRC32K = 94 ,
			PaperSizeType_PaperPRCBig32K = 95 ,
			PaperSizeType_PaperPRCEnvelope1 = 96 ,
			PaperSizeType_PaperPRCEnvelope2 = 97 ,
			PaperSizeType_PaperPRCEnvelope3 = 98 ,
			PaperSizeType_PaperPRCEnvelope4 = 99 ,
			PaperSizeType_PaperPRCEnvelope5 = 100 ,
			PaperSizeType_PaperPRCEnvelope6 = 101 ,
			PaperSizeType_PaperPRCEnvelope7 = 102 ,
			PaperSizeType_PaperPRCEnvelope8 = 103 ,
			PaperSizeType_PaperPRCEnvelope9 = 104 ,
			PaperSizeType_PaperPRCEnvelope10 = 105 ,
			PaperSizeType_PaperPRC16KRotated = 106 ,
			PaperSizeType_PaperPRC32KRotated = 107 ,
			PaperSizeType_PaperPRCBig32KRotated = 108 ,
			PaperSizeType_PaperPRCEnvelope1Rotated = 109 ,
			PaperSizeType_PaperPRCEnvelope2Rotated = 110 ,
			PaperSizeType_PaperPRCEnvelope3Rotated = 111 ,
			PaperSizeType_PaperPRCEnvelope4Rotated = 112 ,
			PaperSizeType_PaperPRCEnvelope5Rotated = 113 ,
			PaperSizeType_PaperPRCEnvelope6Rotated = 114 ,
			PaperSizeType_PaperPRCEnvelope7Rotated = 115 ,
			PaperSizeType_PaperPRCEnvelope8Rotated = 116 ,
			PaperSizeType_PaperPRCEnvelope9Rotated = 117 ,
			PaperSizeType_PaperPRCEnvelope10Rotated = 118 ,
			PaperSizeType_PaperB3 = 300 ,
			PaperSizeType_PaperBusinessCard = 301 ,
			PaperSizeType_PaperThermal = 302 ,
	};


}

}
