#pragma once
#include "System/Object.h"
//#include "System/String.h"
//#include "System/Drawing/Color.h"
#include "CellBorderType.h"
#include "System/Int32.h"
#define STATIC_PIVOTTABLESTYLE03HELPER() 

namespace Aspose {
namespace Cells {
class Style;
class WorksheetCollection;
}
}

namespace Aspose {
namespace Cells {
namespace Pivot {
	class PivotTableStyle03Helper : public Aspose::Cells::System::Object
	{
	private:

			void Init_Vars();
	public:

			static Aspose::Cells::System::Int32 BottomBorder;
			static Aspose::Cells::System::Int32 LeftBorder;
			static Aspose::Cells::System::Int32 RightBorder;
			static Aspose::Cells::System::Int32 TopBorder;
			static Aspose::Cells::System::Int32 HorizonBorder;
			static Aspose::Cells::System::Int32 VerticalBorder;
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleItalicFont(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleCenterAlignment(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleRowSubHeadingIndent(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets , Aspose::Cells::System::Int32 indent , bool rightToLeft);
			static intrusive_ptr<Aspose::Cells::Style> CreateCommonFirstColumnBorder(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateCommonHeaderRowBorder(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateCommonHeaderCellBorder(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleCommonLeftColumnBorderStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleCommonBottomBorderStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable1PageLabel(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable1ColumnHeader0(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable1ColumnHeading1(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable1ColumnHeading2(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable1ColumnHeaderLast(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable1Whole(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable1FirstHeaderCellStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable1RowHeader0(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable1RowHeading1(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets , bool isTable);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable1RowHeading2(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets , bool isTable);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable1RowHeading3(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets , bool isTable);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable1ColumnTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable1RowTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable1ColumnSubtotal(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleCleanRowSubTotal(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleCleanColumnSubTotal(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable1RowSubtotal1(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable1RowSubtotal2(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable1RowSubtotal3(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable1Blank(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable1GrandTotalColumn(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable1GrandTotalRow(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable1SubHeading1BorderStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable2PageLabel(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable2FirstColumnBorder(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable2HeaderRowBorder(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable2SubHeading1BorderStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable2Whole(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable2ColumnTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable2RowTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable2FirstHeaderCellStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable2ColumnHeader0(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable2ColumnHeading1(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable2ColumnHeading2(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable2ColumnSubtotal(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable2RowHeader0(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable2RowHeading1(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets , bool isTable);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable2RowHeading2(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets , bool isTable);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable2RowSubtotal1(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable2RowSubtotal2(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable2RowSubtotal3(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable2GrandTotalRow(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable2GrandTotalColumn(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable3WholeTable(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable3PageLabel(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable3FirstColumnBorder(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable3HeaderCell(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable3RowTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable3ColumnTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable3ColumnHeading1(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable3RowHeader0(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable3RowSubTotal1(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable3RowSubTotal2(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable3ColumnStripeTitleStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable3ColumnStripeDataStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable3ColumnStripeDataTotalStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable3ColumnStripeBorderStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable3GrandRowTotalStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable3SubHeading1BorderStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable3SubHeadingLastBorderStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable3RowSubHeadingLeftBorderStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable3GrandTotalColumnHeaderStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable3GrandTotalColumnStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable4WholeTable(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable4PageLabel(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable4HeaderCell(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable4RowTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable4ColumnTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable4ColumnHeading1(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable4RowHeader0(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable4RowSubTotal1(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable4RowSubTotal2(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable4BlankStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable4GrandRowTotalStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable4GrandTotalColumnHeaderStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable4GrandTotalColumnStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable4RowHeading2(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable4ColumnStripeStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable4ColumnStripeDataStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable4LeftBorderStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable4SubHeading1BorderStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable5PageLabel(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable5PageValue(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable5HeaderCell(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable5ColumnSubTotal(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable5ColumnHeader0(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable5ColumnHeader1(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable5ColumnHeader2(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable5ColumnHeaderLast(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable5RowTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable5ColumnTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable5RowSubHeading1(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable5RowSubTotal1(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable5RowSubTotal2(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable5LeftBorderStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets , Aspose::Cells::CellBorderType linType);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable5GrandTotalColumnStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable5GrandTotalRowStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable5CleanLastColumnheadingBorder(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable5LastRowheadingFont(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable6WholeTable(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable6Page(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable6FirstColumn(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable6HeaderCell(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable6RowTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable6ColumnTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable6ColumnHeader0(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable6ColumnSubtotal(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable6CleanColumnSubtotalHeader(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable6RowSubHeading(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable6RowSubTotal1(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable6RowSubTotal2(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable6SubHeading1BorderStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable6GrandTotalColumnStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable6GrandTotalRowStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable6ColumnColorBorderStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable6ColumnBorderStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable6BlankStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable7Page(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable7HeaderCell(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable7RowTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable7ColumnTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable7ColumnHeader0(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable7ColumnSubHeading(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable7ColumnHeaderLast(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable7RowSubTotal1(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable7RowSubTotal2(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable7RowSubTotal3(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable7RowHeading1(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets , bool isTable);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable7RowHeading2(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets , bool isTable);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable7GrandTotalColumnHeader(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable7GrandTotalColumn(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable7GrandTotalRowHeader(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable7GrandTotalRow(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable7ColumnBorderStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable7SubHeading1BorderStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable7CleanLastSubHeadingBorder(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable7LeftBorderStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable7BlankStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable8Page(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable8RowTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable8ColumnHeader1(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable8ColumnHeader1NoColor(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable8ColumnHeader2(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable8CleanColumnSubTotalFontColor(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable8ColumnSubtotal(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable8RowSubTotal1(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable8RowSubTotal2(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable8RowHeading1(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets , bool isTable);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable8GrandTotalRow(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable8GrandTotalColumnHeaderCell(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable8GrandTotalColumn(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable8SubHeading1BorderStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable8LeftBorder(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable8ColorLeftBorder(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable8DottedLeftBorder(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable8HairLeftBorder(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable8BlankStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable9Page(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable9HeaderCell(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable9RowTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable9ColumnTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable9ColumnHeader0(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable9ColumnSubHeading1(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable9ColumnSubHeading2(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable9ColumnHeaderLast(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable9ColumnSubtotal(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable9LeftBorder(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable9RowSubTotal1(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable9RowSubTotal2(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable9RowSubTotal3(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable9RowHeading1(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets , bool isTable);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable9RowHeading2(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets , bool isTable);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable9GrandTotalColumnHeader(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable9GrandTotalColumn(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable9GrandTotalRow(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable9SubHeading1BorderStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable9ColumnBorderStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable9BlankStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable10Page(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable10HeaderCell(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable10RowTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable10ColumnTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable10ColumnHeader0(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable10ColumnSubHeading(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable10BlankStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable10ColumnHeaderLast(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable10ColumnSubtotal(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable10LeftBorder(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable10RowSubTotal1(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable10RowSubTotal2(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable10RowHeading(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets , bool isTable);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable10GrandTotalRow(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable10GrandTotalColumn(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable10DottedLeftBorder(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable10HairLeftBorder(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleTable10SubHeading1BorderStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleClassicWholeTable(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleClassicPageLabel(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleClassicHeaderCell(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleClassicRowTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleClassicColumnTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleClassicColumnSubHeading(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleClassicBlankStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleClassicColumnSubtotal(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleClassicRowSubTotal(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleClassicRowHeading(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets , bool isTable);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleClassicGrandTotalRow(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleClassicGrandTotalColumn(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleRowSubHeadingBottomBorderStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleClassicSubHeading1BorderStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleClassicColumnBorderStyle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleNonePage(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport1Page(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport1RowTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport1RightTopCell(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport1RowHeading1Head(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport1RowHeading1All(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport1RowHeading1Tail(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport1RowHeading2Head(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport1RowHeading2Tail(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport1RowHeading3Head(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport1RowHeading3All(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport1RowHeading3Tail(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport1FirstRow(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport1GrandTotalRow(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport1GrandTotalRowHeadCell(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport2Page(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport2RowTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport2RightTopCell(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport2RowHeading1Head(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport2RowHeading2Head(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport2RowHeading2Tail(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport2RowHeading3Head(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport2RowHeading3Tail(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport2RowHeadingLastHead(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport2RowHeadingLastTail(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport2GrandTotalRow(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport2Whole(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport1RowSubtotal1(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport1RowSubtotal2(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport1RowSubtotal3(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport3Page(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport3RowTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport3RightTopCell(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport3RowHeading1HeadTail(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport3RowHeading1All(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport3RowHeading2HeadTail(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport3RowHeading3Head(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport3RowHeading3All(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport3RowHeading3Tail(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport3GrandTotalRow(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport4Page(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport4RowTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport4RightTopCell(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport4RowSubtotal1(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport4RowSubtotal2(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport4RowSubtotal3(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport4RowHeading1Head(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport4RowHeading2Head(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport4RowHeading3Head(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport4RowHeading3Tail(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport4RowHeadingLastHead(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport4RowHeadingLastTail(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport4GrandTotalRow(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport5Page(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport5RowTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport5RightTopCell(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport5RowSubtotal1(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport5RowSubtotal2(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport5RowSubtotal3(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport5RowHeading1Head(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport5RowHeading2Head(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport5RowHeading2Tail(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport5RowHeading3Head(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport5RowHeading3Tail(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport5RowHeadingLastHead(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport5RowHeadingLastTail(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport5GrandTotalRow(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport6Whole(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport6Page(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport6RowTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport6RightTopCell(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport6RowHeading1Head(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport6RowHeading1All(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport6RowHeading1Tail(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport6RowHeading2Head(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport6RowHeading2All(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport6RowHeading2Tail(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport6RowHeading3Head(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport6RowHeading3Tail(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport6RowHeadingLastHead(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport6RowHeadingLastTail(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport6GrandTotalRow(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport7Whole(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport7Page(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport7RowTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport7RightTopCell(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport7RowSubtotal1(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport7RowSubtotal2(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport7RowSubtotal3(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport7RowHeading1Head(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport7RowHeading2Head(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport7RowHeading3Head(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport7RowHeading3Tail(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport7RowHeadingLastHead(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport7RowHeadingLastTail(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport7GrandTotalRow(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport8Page(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport8RowTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport8RightTopCell(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport8RowSubtotal1(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport8RowSubtotal2(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport8RowSubtotal3(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport8RowHeading1Head(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport8RowHeading2Head(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport8RowHeading2Tail(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport8RowHeading3Head(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport8RowHeading3Tail(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport8RowHeadingLastHead(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport8RowHeadingLastTail(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport8GrandTotalRow(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport9Page(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport9RowTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport9RightTopCell(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport9RowHeading1HeadAll(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport9RowHeading2Head(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport9RowHeading2All(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport9RowHeading3Head(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport9RowHeading3All(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport9RowHeadingLastHead(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport9GrandTotalRow(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport10Page(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport10RowTitle(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport10RightTopCell(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport10RowHeading1Head(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport10RowHeading1Tail(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport10RowHeading2Head(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport10RowHeading2All(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport10RowHeading2Tail(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport10RowHeading3HeadAll(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport10RowHeading3Tail(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport10RowHeadingLastHead(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport10RowHeadingLastTail(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport10GrandTotalRow(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			static intrusive_ptr<Aspose::Cells::Style> CreateStyleReport10Whole(intrusive_ptr<Aspose::Cells::WorksheetCollection> sheets);
			 PivotTableStyle03Helper();
		public:
			virtual ~PivotTableStyle03Helper();
	};

}

}

}
