#pragma once
namespace Aspose {
namespace Cells {
namespace Pivot {
	enum PivotTableStyleType 

	{

			PivotTableStyleType_None ,
			PivotTableStyleType_PivotTableStyleLight1 ,
			PivotTableStyleType_PivotTableStyleLight2 ,
			PivotTableStyleType_PivotTableStyleLight3 ,
			PivotTableStyleType_PivotTableStyleLight4 ,
			PivotTableStyleType_PivotTableStyleLight5 ,
			PivotTableStyleType_PivotTableStyleLight6 ,
			PivotTableStyleType_PivotTableStyleLight7 ,
			PivotTableStyleType_PivotTableStyleLight8 ,
			PivotTableStyleType_PivotTableStyleLight9 ,
			PivotTableStyleType_PivotTableStyleLight10 ,
			PivotTableStyleType_PivotTableStyleLight11 ,
			PivotTableStyleType_PivotTableStyleLight12 ,
			PivotTableStyleType_PivotTableStyleLight13 ,
			PivotTableStyleType_PivotTableStyleLight14 ,
			PivotTableStyleType_PivotTableStyleLight15 ,
			PivotTableStyleType_PivotTableStyleLight16 ,
			PivotTableStyleType_PivotTableStyleLight17 ,
			PivotTableStyleType_PivotTableStyleLight18 ,
			PivotTableStyleType_PivotTableStyleLight19 ,
			PivotTableStyleType_PivotTableStyleLight20 ,
			PivotTableStyleType_PivotTableStyleLight21 ,
			PivotTableStyleType_PivotTableStyleLight22 ,
			PivotTableStyleType_PivotTableStyleLight23 ,
			PivotTableStyleType_PivotTableStyleLight24 ,
			PivotTableStyleType_PivotTableStyleLight25 ,
			PivotTableStyleType_PivotTableStyleLight26 ,
			PivotTableStyleType_PivotTableStyleLight27 ,
			PivotTableStyleType_PivotTableStyleLight28 ,
			PivotTableStyleType_PivotTableStyleMedium1 ,
			PivotTableStyleType_PivotTableStyleMedium2 ,
			PivotTableStyleType_PivotTableStyleMedium3 ,
			PivotTableStyleType_PivotTableStyleMedium4 ,
			PivotTableStyleType_PivotTableStyleMedium5 ,
			PivotTableStyleType_PivotTableStyleMedium6 ,
			PivotTableStyleType_PivotTableStyleMedium7 ,
			PivotTableStyleType_PivotTableStyleMedium8 ,
			PivotTableStyleType_PivotTableStyleMedium9 ,
			PivotTableStyleType_PivotTableStyleMedium10 ,
			PivotTableStyleType_PivotTableStyleMedium11 ,
			PivotTableStyleType_PivotTableStyleMedium12 ,
			PivotTableStyleType_PivotTableStyleMedium13 ,
			PivotTableStyleType_PivotTableStyleMedium14 ,
			PivotTableStyleType_PivotTableStyleMedium15 ,
			PivotTableStyleType_PivotTableStyleMedium16 ,
			PivotTableStyleType_PivotTableStyleMedium17 ,
			PivotTableStyleType_PivotTableStyleMedium18 ,
			PivotTableStyleType_PivotTableStyleMedium19 ,
			PivotTableStyleType_PivotTableStyleMedium20 ,
			PivotTableStyleType_PivotTableStyleMedium21 ,
			PivotTableStyleType_PivotTableStyleMedium22 ,
			PivotTableStyleType_PivotTableStyleMedium23 ,
			PivotTableStyleType_PivotTableStyleMedium24 ,
			PivotTableStyleType_PivotTableStyleMedium25 ,
			PivotTableStyleType_PivotTableStyleMedium26 ,
			PivotTableStyleType_PivotTableStyleMedium27 ,
			PivotTableStyleType_PivotTableStyleMedium28 ,
			PivotTableStyleType_PivotTableStyleDark1 ,
			PivotTableStyleType_PivotTableStyleDark2 ,
			PivotTableStyleType_PivotTableStyleDark3 ,
			PivotTableStyleType_PivotTableStyleDark4 ,
			PivotTableStyleType_PivotTableStyleDark5 ,
			PivotTableStyleType_PivotTableStyleDark6 ,
			PivotTableStyleType_PivotTableStyleDark7 ,
			PivotTableStyleType_PivotTableStyleDark8 ,
			PivotTableStyleType_PivotTableStyleDark9 ,
			PivotTableStyleType_PivotTableStyleDark10 ,
			PivotTableStyleType_PivotTableStyleDark11 ,
			PivotTableStyleType_PivotTableStyleDark12 ,
			PivotTableStyleType_PivotTableStyleDark13 ,
			PivotTableStyleType_PivotTableStyleDark14 ,
			PivotTableStyleType_PivotTableStyleDark15 ,
			PivotTableStyleType_PivotTableStyleDark16 ,
			PivotTableStyleType_PivotTableStyleDark17 ,
			PivotTableStyleType_PivotTableStyleDark18 ,
			PivotTableStyleType_PivotTableStyleDark19 ,
			PivotTableStyleType_PivotTableStyleDark20 ,
			PivotTableStyleType_PivotTableStyleDark21 ,
			PivotTableStyleType_PivotTableStyleDark22 ,
			PivotTableStyleType_PivotTableStyleDark23 ,
			PivotTableStyleType_PivotTableStyleDark24 ,
			PivotTableStyleType_PivotTableStyleDark25 ,
			PivotTableStyleType_PivotTableStyleDark26 ,
			PivotTableStyleType_PivotTableStyleDark27 ,
			PivotTableStyleType_PivotTableStyleDark28 ,
			PivotTableStyleType_Custom ,
	};


}

}

}
